# Generated by Django 3.1.1 on 2020-09-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('hero_text', models.CharField(max_length=500)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_five', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_six', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_seven', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_eight', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_nine', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
