# Generated by Django 3.1.1 on 2020-09-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
