# Generated by Django 3.1.1 on 2020-09-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_app', '0003_remove_event_hero_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hero_image',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
