# Generated by Django 3.1.1 on 2020-09-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band_app', '0005_auto_20200915_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_image',
            new_name='image',
        ),
    ]
