# Generated by Django 3.1.1 on 2020-09-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band_app', '0006_auto_20200915_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
