# Generated by Django 3.1.1 on 2020-09-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_app', '0008_auto_20200915_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
