# Generated by Django 3.1.1 on 2020-09-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_app', '0009_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
