# Generated by Django 3.1.1 on 2020-09-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band_app', '0010_auto_20200916_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='venue1',
            new_name='artiste1',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='venue2',
            new_name='artiste2',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='venue3',
            new_name='artiste3',
        ),
    ]
