# Generated by Django 3.1.1 on 2020-09-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_app', '0014_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
