# Generated by Django 3.1.1 on 2020-09-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band_app', '0014_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
