# Generated by Django 3.1.1 on 2020-09-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_app', '0015_auto_20200917_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(),
        ),
    ]
