# Generated by Django 3.1.1 on 2020-09-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_app', '0015_remove_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
